### ISSUE TITLE
Bothub Deployment instructions

### ISSUE THREAD

**Issue by GiantRobato** [hahaga/line-bot#19]
To deploy to bothub we need to have correct credentials file in: `~/.bothub`

Instructions on the README should include how to deploy to bothub.

**Comment by Wakahisa** [comment]
Added in instructions to run bot and how to test it. Might not work if everyone requires their own line developer account and bothub account.

**Comment by Wakahisa** [comment]
I used this link to get the bot running 

https://medium.com/bothub-studio/build-a-line-chatbot-in-python-2d78b8452d97
