### ISSUE TITLE
Basic Backend

### ISSUE THREAD

**Issue by GiantRobato** [hahaga/line-bot#2]
- which DB? Mongo? Dynamo? MySql
- Language? JS, python, ruby

- [x] Definition
  - [x] Backend: (DynamoDB)
  - [x] Language: Python
- [x] endpoints
  - [x] `GET /fortune`
    - return a single fortune randomly
    - returns `<fortune_model>`
  - ~~[ ] `GET /fortune/{id}`~~
    - ~~returns a fortune by id where id is a uuid~~
    - ~~returns `<fortune_model>`~~
  - [x] `GET /fortune/all`
    - get all fortunes
    - returns `list[<fortune_model>]`
  - [x] `POST /fortune`
    - expects `<fortune_post_model>`
  - [x] `PUT /fortune/{id}`
    - toggles approval
    - expects `<fortune_approval_model>`
  - [x] `DELETE /fortune/{id}`

Models
====
fortune_model
```
{
  "fortune": {
      "approved": true, 
      "author": "Random", 
      "fortune": "A friend asks only for your time not your money.", 
      "id": <uuid>
  }
}
```
fortune_post_model
```
{
  "author": "Random", 
  "fortune": "A friend asks only for your time not your money.",
}
```
fortune_approval_model
```
{
  "id": <uuid>
}
```

**Comment by GiantRobato** [comment]
Endpoints

- `GET /fortune`
    - return a single fortune
- `GET /fortune/{id}`
    - returns a fortune by id
- `GET /fortune/all`
    - get all fortunes
- `POST /fortune`
    - author
    - fortune
- `PUT /fortune/{id}`
    - will toggle approval
- `DELETE /fortune/{id}`

**Comment by lottiely** [comment]
Got some of the POST working today. :)

**Comment by lottiely** [comment]
Finished
- `POST/fortune/`
- `GET /fortune` 
- `GET /fortune/all`  
- `DELETE /fortune/{id}`

Pending
- `PUT /fortune/{id}`

Remove
- `GET /fortune/{id}`

Related commits b5fba8df3d7eea1748882725c83ee3c620f7b202 178da46359401cd73add00529c7a8f832cc99e25

**Comment by GiantRobato** [comment]
POST, PUT, and DELETE aren't done/routed yet
